version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    #    env_file: .env
    command: gunicorn gambo.wsgi:application --bind 0.0.0.0:8000

  nginx:
    restart: always
    build: ./deployment/nginx/
    ports:
      - "8002:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
