# Generated by Django 5.1.4 on 2025-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("born", models.DateField()),
                ("height", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("slug", models.SlugField(unique=True)),
                ("type", models.CharField(max_length=100)),
            ],
        ),
    ]
