# Generated by Django 3.1.2 on 2020-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
