# Generated by Django 5.1.4 on 2025-01-13 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("genres", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("poster", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("thumbnail", models.URLField(max_length=500)),
                ("release_date", models.DateField()),
                ("views", models.IntegerField(default=0)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="series.season",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("season", "number")},
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("year", models.IntegerField()),
                (
                    "imdb",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("classification", models.IntegerField(default=0)),
                ("thumbnail", models.URLField(max_length=500)),
                ("cover", models.URLField(max_length=500)),
                ("trailer_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
                ("is_free", models.BooleanField(default=False)),
                ("language", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("network", models.CharField(max_length=100)),
                ("total_seasons", models.IntegerField(default=1)),
                ("release_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("actors", models.ManyToManyField(to="core.actor")),
                ("genres", models.ManyToManyField(to="genres.genre")),
            ],
            options={
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="season",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="series.series",
            ),
        ),
        migrations.CreateModel(
            name="EpisodeSubtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("subtitle_url", models.URLField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="series.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["language"],
                "unique_together": {("episode", "language")},
            },
        ),
        migrations.CreateModel(
            name="EpisodeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("4K", "4K"),
                            ("1080p", "1080p"),
                            ("720p", "720p"),
                            ("480p", "480p"),
                            ("360p", "360p"),
                        ],
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField()),
                ("size", models.FloatField(help_text="File size in MB")),
                ("duration", models.IntegerField(help_text="Duration in seconds")),
                ("codec", models.CharField(max_length=50)),
                ("bitrate", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="series.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["-quality"],
                "unique_together": {("episode", "quality")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("series", "number")},
        ),
        migrations.CreateModel(
            name="SeriesReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="series.series",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("series", "user")},
            },
        ),
    ]
