# Generated by Django 5.1.4 on 2025-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="cover",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
