# Generated by Django 3.1.2 on 2020-10-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201014_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
